name: Deploy

on:
  merge:
    branches: [ "main" ]

jobs:
  deploy_ecs:
    runs-on: ubuntu-latest
    needs: create_push_image
    steps:
      - name: Render Amazon ECS task definition
        id: render-web-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: wordpress
          image: wordpress:latest
          environment-variables: "LOG_LEVEL=info"

      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-web-container.outputs.task-definition }}
          service: my-service
          cluster: my-cluster